apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
  - ../../base
patchesStrategicMerge:
  - deployment-patch.yaml
secretGenerator:
  - name: finitech-secrets
    literals:
      - connection-string=Host=staging-postgres;Port=5432;Database=finitech;Username=finitech;Password=staging-password
      - rabbitmq-host=staging-rabbitmq
      - redis-connection=staging-redis:6379
